<?php

namespace Gdr\AvatarBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FateController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Gdr\AvatarBundle\Controller\FateController();
        return $instance;
    }
}
