<?php

namespace Gdr\GameBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MarketController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Gdr\GameBundle\Controller\MarketController();
        return $instance;
    }
}
