<?php

namespace Proxies\__CG__\Gdr\GameBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Chat extends \Gdr\GameBundle\Entity\Chat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'id', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'body', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'castBody', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'type', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'tag', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'freeTag', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'sender', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'senderName', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'senderRace', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'senderRaceIcon', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'senderDressIcon', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'senderDressName', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'senderLevelIcon', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'senderRankName', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'receiverWhispered', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'createdAt', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'location', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'spell', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'special', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'skill', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'extra', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'cssClass', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'raceLanguage', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'language', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'combat'];
        }

        return ['__isInitialized__', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'id', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'body', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'castBody', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'type', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'tag', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'freeTag', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'sender', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'senderName', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'senderRace', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'senderRaceIcon', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'senderDressIcon', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'senderDressName', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'senderLevelIcon', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'senderRankName', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'receiverWhispered', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'createdAt', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'location', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'spell', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'special', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'skill', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'extra', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'cssClass', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'raceLanguage', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'language', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Chat' . "\0" . 'combat'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Chat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBody($body)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBody', [$body]);

        return parent::setBody($body);
    }

    /**
     * {@inheritDoc}
     */
    public function getBody()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBody', []);

        return parent::getBody();
    }

    /**
     * {@inheritDoc}
     */
    public function setTag($tag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTag', [$tag]);

        return parent::setTag($tag);
    }

    /**
     * {@inheritDoc}
     */
    public function getTag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTag', []);

        return parent::getTag();
    }

    /**
     * {@inheritDoc}
     */
    public function setFreeTag($freeTag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFreeTag', [$freeTag]);

        return parent::setFreeTag($freeTag);
    }

    /**
     * {@inheritDoc}
     */
    public function getFreeTag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFreeTag', []);

        return parent::getFreeTag();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenderName($senderName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenderName', [$senderName]);

        return parent::setSenderName($senderName);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenderName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenderName', []);

        return parent::getSenderName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenderRace($senderRace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenderRace', [$senderRace]);

        return parent::setSenderRace($senderRace);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenderRace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenderRace', []);

        return parent::getSenderRace();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation(\Gdr\GameBundle\Entity\Location $location = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$location]);

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function getSenderRaceIcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenderRaceIcon', []);

        return parent::getSenderRaceIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenderRaceIcon($senderRaceIcon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenderRaceIcon', [$senderRaceIcon]);

        return parent::setSenderRaceIcon($senderRaceIcon);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenderDressIcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenderDressIcon', []);

        return parent::getSenderDressIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenderDressIcon($senderDressIcon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenderDressIcon', [$senderDressIcon]);

        return parent::setSenderDressIcon($senderDressIcon);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getReceiverWhispered()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReceiverWhispered', []);

        return parent::getReceiverWhispered();
    }

    /**
     * {@inheritDoc}
     */
    public function setReceiverWhispered($receiverWhispered)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReceiverWhispered', [$receiverWhispered]);

        return parent::setReceiverWhispered($receiverWhispered);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenderDressName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenderDressName', []);

        return parent::getSenderDressName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenderDressName($senderDressName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenderDressName', [$senderDressName]);

        return parent::setSenderDressName($senderDressName);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecial', []);

        return parent::getSpecial();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecial($special)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecial', [$special]);

        return parent::setSpecial($special);
    }

    /**
     * {@inheritDoc}
     */
    public function getCastBody()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCastBody', []);

        return parent::getCastBody();
    }

    /**
     * {@inheritDoc}
     */
    public function setCastBody($castBody)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCastBody', [$castBody]);

        return parent::setCastBody($castBody);
    }

    /**
     * {@inheritDoc}
     */
    public function setSpell(\Gdr\UserBundle\Entity\Spell $spell = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpell', [$spell]);

        return parent::setSpell($spell);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpell()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpell', []);

        return parent::getSpell();
    }

    /**
     * {@inheritDoc}
     */
    public function setSender(\Gdr\UserBundle\Entity\Personage $sender = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSender', [$sender]);

        return parent::setSender($sender);
    }

    /**
     * {@inheritDoc}
     */
    public function getSender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSender', []);

        return parent::getSender();
    }

    /**
     * {@inheritDoc}
     */
    public function getExtra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtra', []);

        return parent::getExtra();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtra($extra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtra', [$extra]);

        return parent::setExtra($extra);
    }

    /**
     * {@inheritDoc}
     */
    public function getSkill()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSkill', []);

        return parent::getSkill();
    }

    /**
     * {@inheritDoc}
     */
    public function setSkill($skill)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSkill', [$skill]);

        return parent::setSkill($skill);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenderLevelIcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenderLevelIcon', []);

        return parent::getSenderLevelIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenderLevelIcon($senderLevelIcon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenderLevelIcon', [$senderLevelIcon]);

        return parent::setSenderLevelIcon($senderLevelIcon);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenderRankName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenderRankName', []);

        return parent::getSenderRankName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenderRankName($senderRankName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenderRankName', [$senderRankName]);

        return parent::setSenderRankName($senderRankName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCssClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCssClass', []);

        return parent::getCssClass();
    }

    /**
     * {@inheritDoc}
     */
    public function setCssClass($cssClass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCssClass', [$cssClass]);

        return parent::setCssClass($cssClass);
    }

    /**
     * {@inheritDoc}
     */
    public function setRaceLanguage(\Gdr\RaceBundle\Entity\Race $raceLanguage = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaceLanguage', [$raceLanguage]);

        return parent::setRaceLanguage($raceLanguage);
    }

    /**
     * {@inheritDoc}
     */
    public function getRaceLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaceLanguage', []);

        return parent::getRaceLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguage(\Gdr\UserBundle\Entity\Language $language = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguage', [$language]);

        return parent::setLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguage', []);

        return parent::getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function getCombat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCombat', []);

        return parent::getCombat();
    }

    /**
     * {@inheritDoc}
     */
    public function setCombat($combat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCombat', [$combat]);

        return parent::setCombat($combat);
    }

}
