<?php

namespace Proxies\__CG__\Gdr\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Gravestone extends \Gdr\UserBundle\Entity\Gravestone implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Gravestone' . "\0" . 'id', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Gravestone' . "\0" . 'nickname', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Gravestone' . "\0" . 'surname', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Gravestone' . "\0" . 'deathAt', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Gravestone' . "\0" . 'deathAge', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Gravestone' . "\0" . 'inFamilyGrave', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Gravestone' . "\0" . 'message', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Gravestone' . "\0" . 'typeYear'];
        }

        return ['__isInitialized__', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Gravestone' . "\0" . 'id', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Gravestone' . "\0" . 'nickname', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Gravestone' . "\0" . 'surname', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Gravestone' . "\0" . 'deathAt', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Gravestone' . "\0" . 'deathAge', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Gravestone' . "\0" . 'inFamilyGrave', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Gravestone' . "\0" . 'message', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Gravestone' . "\0" . 'typeYear'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Gravestone $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNickname($nickname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNickname', [$nickname]);

        return parent::setNickname($nickname);
    }

    /**
     * {@inheritDoc}
     */
    public function getNickname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNickname', []);

        return parent::getNickname();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurname($surname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurname', [$surname]);

        return parent::setSurname($surname);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurname', []);

        return parent::getSurname();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeathAt($deathAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeathAt', [$deathAt]);

        return parent::setDeathAt($deathAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeathAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeathAt', []);

        return parent::getDeathAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setInFamilyGrave($inFamilyGrave)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInFamilyGrave', [$inFamilyGrave]);

        return parent::setInFamilyGrave($inFamilyGrave);
    }

    /**
     * {@inheritDoc}
     */
    public function getInFamilyGrave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInFamilyGrave', []);

        return parent::getInFamilyGrave();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessage($message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessage', [$message]);

        return parent::setMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessage', []);

        return parent::getMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeathAge($deathAge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeathAge', [$deathAge]);

        return parent::setDeathAge($deathAge);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeathAge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeathAge', []);

        return parent::getDeathAge();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeYear($typeYear)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeYear', [$typeYear]);

        return parent::setTypeYear($typeYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeYear', []);

        return parent::getTypeYear();
    }

}
