<?php

namespace Proxies\__CG__\Gdr\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Esilio extends \Gdr\UserBundle\Entity\Esilio implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Esilio' . "\0" . 'id', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Esilio' . "\0" . 'reason', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Esilio' . "\0" . 'days', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Esilio' . "\0" . 'until', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Esilio' . "\0" . 'moderator', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Esilio' . "\0" . 'banned', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Esilio' . "\0" . 'personage', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Esilio' . "\0" . 'createdAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Esilio' . "\0" . 'id', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Esilio' . "\0" . 'reason', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Esilio' . "\0" . 'days', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Esilio' . "\0" . 'until', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Esilio' . "\0" . 'moderator', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Esilio' . "\0" . 'banned', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Esilio' . "\0" . 'personage', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Esilio' . "\0" . 'createdAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Esilio $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setReason($reason)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReason', [$reason]);

        return parent::setReason($reason);
    }

    /**
     * {@inheritDoc}
     */
    public function getReason()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReason', []);

        return parent::getReason();
    }

    /**
     * {@inheritDoc}
     */
    public function setDays($days)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDays', [$days]);

        return parent::setDays($days);
    }

    /**
     * {@inheritDoc}
     */
    public function getDays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDays', []);

        return parent::getDays();
    }

    /**
     * {@inheritDoc}
     */
    public function setUntil($until)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUntil', [$until]);

        return parent::setUntil($until);
    }

    /**
     * {@inheritDoc}
     */
    public function getUntil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUntil', []);

        return parent::getUntil();
    }

    /**
     * {@inheritDoc}
     */
    public function setModerator(\Gdr\UserBundle\Entity\Personage $moderator = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModerator', [$moderator]);

        return parent::setModerator($moderator);
    }

    /**
     * {@inheritDoc}
     */
    public function getModerator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModerator', []);

        return parent::getModerator();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setBanned(\Gdr\UserBundle\Entity\User $banned = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBanned', [$banned]);

        return parent::setBanned($banned);
    }

    /**
     * {@inheritDoc}
     */
    public function getBanned()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBanned', []);

        return parent::getBanned();
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonage', []);

        return parent::getPersonage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonage($personage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonage', [$personage]);

        return parent::setPersonage($personage);
    }

}
