<?php

namespace Proxies\__CG__\Gdr\GameBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Letter extends \Gdr\GameBundle\Entity\Letter implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'id', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'category', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'senderName', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'body', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'oldBody', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'isRead', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'isDeleted', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'sender', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'receiver', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'receiverName', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'senderLevelIcon', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'senderRankName', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'senderRaceIcon', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'senderRaceName', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'isForward', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'nameAsAdmin', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'nameAsMod', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'nameAsFate', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'background', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'createdAt', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'special'];
        }

        return ['__isInitialized__', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'id', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'category', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'senderName', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'body', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'oldBody', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'isRead', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'isDeleted', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'sender', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'receiver', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'receiverName', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'senderLevelIcon', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'senderRankName', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'senderRaceIcon', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'senderRaceName', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'isForward', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'nameAsAdmin', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'nameAsMod', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'nameAsFate', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'background', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'createdAt', '' . "\0" . 'Gdr\\GameBundle\\Entity\\Letter' . "\0" . 'special'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Letter $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenderName($senderName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenderName', [$senderName]);

        return parent::setSenderName($senderName);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenderName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenderName', []);

        return parent::getSenderName();
    }

    /**
     * {@inheritDoc}
     */
    public function setBody($body)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBody', [$body]);

        return parent::setBody($body);
    }

    /**
     * {@inheritDoc}
     */
    public function getBody()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBody', []);

        return parent::getBody();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsRead($isRead)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsRead', [$isRead]);

        return parent::setIsRead($isRead);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsRead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsRead', []);

        return parent::getIsRead();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDeleted($isDeleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDeleted', [$isDeleted]);

        return parent::setIsDeleted($isDeleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDeleted', []);

        return parent::getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setSender(\Gdr\UserBundle\Entity\Personage $sender = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSender', [$sender]);

        return parent::setSender($sender);
    }

    /**
     * {@inheritDoc}
     */
    public function getSender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSender', []);

        return parent::getSender();
    }

    /**
     * {@inheritDoc}
     */
    public function setReceiver(\Gdr\UserBundle\Entity\Personage $receiver = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReceiver', [$receiver]);

        return parent::setReceiver($receiver);
    }

    /**
     * {@inheritDoc}
     */
    public function getReceiver()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReceiver', []);

        return parent::getReceiver();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getReceiverName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReceiverName', []);

        return parent::getReceiverName();
    }

    /**
     * {@inheritDoc}
     */
    public function setReceiverName($receiverName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReceiverName', [$receiverName]);

        return parent::setReceiverName($receiverName);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenderLevelIcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenderLevelIcon', []);

        return parent::getSenderLevelIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenderLevelIcon($senderLevelIcon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenderLevelIcon', [$senderLevelIcon]);

        return parent::setSenderLevelIcon($senderLevelIcon);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenderRankName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenderRankName', []);

        return parent::getSenderRankName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenderRankName($senderRankName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenderRankName', [$senderRankName]);

        return parent::setSenderRankName($senderRankName);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenderRaceName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenderRaceName', []);

        return parent::getSenderRaceName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenderRaceName($senderRaceName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenderRaceName', [$senderRaceName]);

        return parent::setSenderRaceName($senderRaceName);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenderRaceIcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenderRaceIcon', []);

        return parent::getSenderRaceIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenderRaceIcon($senderRaceIcon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenderRaceIcon', [$senderRaceIcon]);

        return parent::setSenderRaceIcon($senderRaceIcon);
    }

    /**
     * {@inheritDoc}
     */
    public function getOldBody()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOldBody', []);

        return parent::getOldBody();
    }

    /**
     * {@inheritDoc}
     */
    public function setOldBody($oldBody)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOldBody', [$oldBody]);

        return parent::setOldBody($oldBody);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsForward()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsForward', []);

        return parent::getIsForward();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsForward($isForward)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsForward', [$isForward]);

        return parent::setIsForward($isForward);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameAsFate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameAsFate', []);

        return parent::getNameAsFate();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameAsFate($nameAsFate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameAsFate', [$nameAsFate]);

        return parent::setNameAsFate($nameAsFate);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameAsMod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameAsMod', []);

        return parent::getNameAsMod();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameAsMod($nameAsMod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameAsMod', [$nameAsMod]);

        return parent::setNameAsMod($nameAsMod);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameAsAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameAsAdmin', []);

        return parent::getNameAsAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameAsAdmin($nameAsAdmin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameAsAdmin', [$nameAsAdmin]);

        return parent::setNameAsAdmin($nameAsAdmin);
    }

    /**
     * {@inheritDoc}
     */
    public function setBackground(\Gdr\GameBundle\Entity\LetterBackground $background = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBackground', [$background]);

        return parent::setBackground($background);
    }

    /**
     * {@inheritDoc}
     */
    public function getBackground()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBackground', []);

        return parent::getBackground();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory($category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecial', []);

        return parent::getSpecial();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecial($special)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecial', [$special]);

        return parent::setSpecial($special);
    }

}
