<?php

namespace Gdr\MeteoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MeteoMonthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeteoMonthRepository extends EntityRepository
{
}
