<?php

namespace Gdr\MeteoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MeteoWindRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeteoWindRepository extends EntityRepository
{
    public function findRandomWind(){
        $query = $this->createQueryBuilder("mw")
            ->andWhere("mw.isRandom = :is_random")
            ->setParameter("is_random", true);

        $results = $query->getQuery()->getResult();

        shuffle($results);
        return array_pop($results);
    }
}
