<?php

namespace Gdr\MeteoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MeteoCombinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeteoCombinationRepository extends EntityRepository
{
}
