<?php

namespace Gdr\MeteoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MoonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoonRepository extends EntityRepository
{
    /**
     * @param $sort
     * @return \Gdr\MeteoBundle\Entity\Moon
     */
    public function findNewMoonBySort($sort){
        $new_moon = $this->createQueryBuilder("m")
            ->where("m.sort > ".$sort)
            ->setMaxResults(1)
            ->orderBy('m.sort', 'ASC')
            ->getQuery()
            ->getOneOrNullResult();

        if(is_null($new_moon)){
            $new_moon = $this->createQueryBuilder("m")
                ->where("m.sort > 0")
                ->setMaxResults(1)
                ->orderBy('m.sort', 'ASC')
                ->getQuery()
                ->getOneOrNullResult();
        }

        return $new_moon;
    }
}
