<?php

namespace Gdr\MeteoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MoonStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoonStatusRepository extends EntityRepository
{
    public function getMoon()
    {
        return $this->createQueryBuilder('ms')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
