<?php

namespace Gdr\ItemsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PropertyItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyItemRepository extends EntityRepository
{
}
