imports:
    - { resource: config.yml }

framework:
    profiler:
        enabled: true
    router:   { resource: "%kernel.root_dir%/config/routing_admin.yml" }

web_profiler:
    toolbar: false
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:               fingers_crossed
            action_level:       error
            handler:            nested
        #            formatter:          monolog.formatter.ip_request
        #        grouped:
        #            type:               group
        #            members:            [streamed, swift]
        nested:
            type:  rotating_file
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 30

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text: ~
        sonata.block.service.rss: ~

sonata_admin:
    title:      Shenteon

sonata_doctrine_orm_admin:
    entity_manager: ~
