imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @GdrSiteBundle/Resources/config/services.yml }
    - { resource: @GdrUserBundle/Resources/config/services.yml }
    - { resource: @GdrGameBundle/Resources/config/services.yml }
    - { resource: @GdrAdministrationBundle/Resources/config/admin.yml }
    - { resource: @GdrAdministrationBundle/Resources/config/services.yml }
    - { resource: bundles/all.yml }

framework:
    translator:      { fallback: "%locale%" }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: v1.0.65
    default_locale:  "%locale%"
    trusted_proxies: [127.0.0.1, 192.0.0.1, 10.0.0.0/8, 46.165.252.196]
    session:
        cookie_lifetime: 0
        save_path: "%kernel.root_dir%/Sessions/"
        cookie_httponly: false
    fragments:       ~
    trusted_hosts: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: true
    bundles:        [GdrSiteBundle, GdrGameBundle, GdrAvatarBundle, GdrAdministrationBundle, GdrUserBundle]
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs
        uglifycss:
            bin: /usr/local/bin/uglifycss

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: smtp
    host:      shenteon.com
    username:  gestione@shenteon.com
    password:  Um3ogRw37hLX#
    encryption: ssl
    auth_mode: login
    port: 465
    #spool:     { type: memory }

monolog:
    handlers:
        cron:
            type: stream
            path: %kernel.logs_dir%/cron.log
            level: info
            channels: [cron]
