jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Gdr\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_ALLOWED_TO_SWITCH, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_SONATA_ADMIN]

    providers:
        database:
            entity: { class: GdrUserBundle:User, property: email }

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /gdr             # sovrascritta dal listener
                success_handler: authentication_handler
                csrf_provider: form.csrf_provider
                csrf_parameter: _csrf_token
            logout:
                path:   /logout
                target: /
                success_handler: authentication_handler
                invalidate_session: true
            anonymous: ~
            switch_user: true

    access_control:
        - { path: ^/gdr/*, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/logout, roles: ROLE_USER }
        - { path: ^/utente/*, roles: ROLE_USER }
        - { path: ^/admin/*, roles: ROLE_ADMIN }
        - { path: ^/gdr/admin/*, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
