parameters:
#    gdr_avatar.example.class: Gdr\AvatarBundle\Example

services:
#    gdr_avatar.example:
#        class: %gdr_avatar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
