<?php

namespace Gdr\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CombatSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CombatSetRepository extends EntityRepository
{
    public function getSetsByPersonage($personage){
        return $this->createQueryBuilder('cs')
            ->addSelect('COALESCE(cl.setLevel, 0) as level')
            ->leftJoin('GdrGameBundle:CombatLearned', 'cl', 'WITH', 'cs.id = cl.combatSet AND cl.personage = '.$personage)
            ->orderBy('cs.sort', 'ASC')
            ->getQuery()
            ->getResult();
    }

    public function getSetsByPersonageArray($personage){
        return $this->createQueryBuilder('cs')
            ->addSelect('COALESCE(cl.setLevel, 0) as level')
            ->leftJoin('GdrGameBundle:CombatLearned', 'cl', 'WITH', 'cs.id = cl.combatSet AND cl.personage = '.$personage)
            ->orderBy('cs.sort', 'ASC')
            ->getQuery()
            ->getArrayResult();
    }
}
