<?php

namespace Gdr\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CombatLearnedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CombatLearnedRepository extends EntityRepository
{
    public function getTotalLearnedForPersonage($pg){
        return $this->createQueryBuilder('cl')
            ->select("COUNT(cl.id) as total")
            ->andWhere('cl.personage = :pg')
            ->setParameter('pg', $pg)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getTotalPointsForPersonage($pg){
        return $this->createQueryBuilder('cl')
            ->select("SUM(cl.level) as total")
            ->andWhere('cl.personage = :pg')
            ->setParameter('pg', $pg)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
