<?php

namespace Gdr\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EdittoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdittoRepository extends EntityRepository
{
    public function findSortedEditti(){
        return $this->createQueryBuilder("e")
            ->orderBy("e.sort", "ASC")
            ->getQuery()->execute();
    }
}
