<?php

namespace Gdr\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ForumCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumCategoryRepository extends EntityRepository
{
    public function findCategoriesForMod()
    {
        return $this->createQueryBuilder('fc')
            ->innerJoin('GdrGameBundle:Forum', 'f', 'WITH', 'f.id = fc.forum')
            ->andWhere('f.type = :public OR f.type = :mod')
            ->setParameter('public', Forum::TYPE_PUBLIC)
            ->setParameter('mod', Forum::TYPE_MOD)
            ->orderBy("fc.sort", "ASC")
            ->getQuery()
            ->getResult();
    }

    public function findPrivateJunk()
    {

        return $this->createQueryBuilder('fc')
            ->innerJoin('GdrGameBundle:Forum', 'f', 'WITH', 'f.id = fc.forum')
            ->andWhere('f.type = :gest')
            ->setParameter('gest', Forum::TYPE_GESTIONE)
            ->andWhere('fc.isJunk = true')
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findEnclaveForumCategories($enclave){
        return $this->createQueryBuilder("fc")
            ->innerJoin("fc.forum", "f")
            ->andWhere("f.enclave = :enclave")
            ->setParameter("enclave", $enclave)
            ->orderBy("fc.sort")
            ->getQuery()
            ->getResult();
    }

    public function findCategoryByIdAndEnclave($id, $enclave){
        return $this->createQueryBuilder("fc")
            ->innerJoin("fc.forum", "f")
            ->andWhere("f.enclave = :enclave")
            ->andWhere("f.type = :type")
            ->andWhere("fc.id = :id")
            ->setParameter("type", Forum::TYPE_ENCLAVE)
            ->setParameter("enclave", $enclave)
            ->setParameter("id", $id)
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }

    public function findCategoryByIdAndClan($id, $clan){
        return $this->createQueryBuilder("fc")
            ->innerJoin("fc.forum", "f")
            ->andWhere("f.enclave = :enclave")
            ->andWhere("f.type = :type")
            ->andWhere("fc.id = :id")
            ->setParameter("type", Forum::TYPE_CLAN)
            ->setParameter("enclave", $clan)
            ->setParameter("id", $id)
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }
}
