<?php

namespace Gdr\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LoginArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginArchiveRepository extends EntityRepository
{
    public function findSameIps(){
        $a = $this->createQueryBuilder('la')
            ->innerJoin('GdrGameBundle:LoginArchive', 'la2', 'WITH', 'la.user != la2.user AND la.ip = la2.ip')
            ->andWhere('la.user != 1 AND la.user != 2 and la.user != 3 and la.user != 6')
            ->andWhere('la2.user != 1 AND la2.user != 2 and la2.user != 3 and la2.user != 6')
            ->orderBy('la.ip')
            ->addOrderBy('la.personage')
            ->addOrderBy('la.createdAt', 'DESC')
            ->getQuery()
            ->setFirstResult(1)
            ->setMaxResults(30)
            ->getArrayResult()
        ; dump($a);exit;
//            ->getResult();
    }

    public function cleanOldest(){
        return $this->createQueryBuilder('la')
            ->delete()
            ->where('la.createdAt <= :date')
            ->setParameter('date', new \DateTime('- 2 months'))
            ->getQuery()
            ->execute()
            ;
    }
}
