<?php

namespace Gdr\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ManualeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManualeRepository extends EntityRepository
{
    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getActive(){
        return $this->createQueryBuilder("m")
            ->andWhere("m.active = :active")
            ->setParameter("active", true);
    }

    public function getSortedActive(){
        return $this->getActive()
            ->orderBy("m.sort", "ASC");
    }

    /**
     * @return mixed
     */
    public function findSorted(){
        return $this->getSortedActive()
            ->getQuery()->execute();
    }

    public function findSortedSite(){
        return $this->getSortedActive()
            ->andWhere('m.isForSite = true')
            ->getQuery()->getResult();
    }
}
