<?php

namespace Gdr\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LoginArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagChatRepository extends EntityRepository
{
    public function findTagsForLocation($location)
    {
        $tags = $this->createQueryBuilder('tc')
            ->andWhere('tc.location = :id')
            ->setParameter('id', $location)
            ->orderBy('tc.name', 'ASC')
            ->getQuery()
            ->getResult()
            ;

        $return = array();

        foreach ($tags as $tag){
            $return[$tag->getName()] = $tag->getName();
        }

        return $return;
    }
}
