<?php

namespace Gdr\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends EntityRepository
{
    public function getAllByPersonageQuery($personage){
        return $this->createQueryBuilder('t')
            ->innerJoin('t.type', 'tt')
            ->addSelect('t.createdAt, t.amount, t.note, t.isPlus, tt.name AS typeName')
            ->andWhere('t.subject = :personage')
            ->setParameter('personage', $personage->getId())
            ->addOrderBy('t.createdAt', 'desc')
            ->setMaxResults(100)
            ->getQuery()
        ;
    }

    public function findAllByPersonage($personage)
    {
        return $this->createQueryBuilder('t')
            ->select('t.id')
            ->andWhere('t.subject = :personage')
            ->setParameter('personage', $personage)
            ->setMaxResults(100)
            ->getQuery()
            ->getResult()
        ;
    }

    public function deleteOldest($ids)
    {
        return $this->createQueryBuilder('t')
            ->delete()
            ->andWhere('t.id IN :ids')
            ->setParameter('ids', $ids)
        ;
    }
}
