<?php

namespace Gdr\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GravestoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GravestoneRepository extends EntityRepository
{
    protected function getBaseQuery(){
        return $this->createQueryBuilder("g")
            ->orderBy("g.surname", "ASC");
    }

    /**
     * @return \Doctrine\ORM\Query
     */
    public function getGravesWithoutFamily(){
        return $this->getBaseQuery()
            ->andWhere("s.inFamilyGrave = 0")
            ->getQuery();
    }

    /**
     * @return \Doctrine\ORM\Query
     */
    public function getGravesWithFamily(){
        return $this->getBaseQuery()
            ->andWhere("s.inFamilyGrave = 1")
            ->getQuery();
    }
}
