<?php

namespace Gdr\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends EntityRepository
{
    public function getLanguagesByPersonage($pg)
    {
        return $this->createQueryBuilder('l')
            ->innerJoin('l.race', 'r')
            ->andWhere('l.personage = :pg')
            ->setParameter('pg', $pg)
            ->groupBy('l.race')
            ->getQuery()
            ->getResult();
    }

    public function getLanguagesByPersonageAndRaceWithCache($pg, $race)
    {
        return $this->createQueryBuilder('l')
            ->innerJoin('l.race', 'r')
            ->andWhere('l.personage = :pg')
            ->setParameter('pg', $pg)
            ->andWhere('l.race = :race')
            ->setParameter('race', $race)
            ->groupBy('l.race')
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true, 60 * 5)
            ->getResult();
    }
}
