<?php

namespace Gdr\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WeddingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeddingRepository extends EntityRepository
{
    public function getActiveMarriages(){
        return $this->createQueryBuilder("w")
            ->andWhere("w.isDivorced = false")
            ->orderBy("w.createdAt", "DESC")
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $personage
     * @return \Gdr\UserBundle\Entity\Wedding
     */
    public function findActiveMarriageByPersonage($personage){
        $qb = $this->createQueryBuilder("w")
            ->andWhere("w.isDivorced = false")
            ->andWhere("w.groom = :id OR w.bride = :id")
            ->setMaxResults(1)
            ->getQuery()
            ->setParameters(array(
                "id" => $personage
            ))->getOneOrNullResult();

        return $qb;

    }
}
