<?php

namespace Gdr\AvatarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiaryRepository extends EntityRepository
{
    public function getQueryDiariesByPersonage($personage_id, $isOwner = false)
    {
        $qb = $this->createQueryBuilder('d')
        ->andWhere('d.personage = :personage')
        ->setParameter('personage', $personage_id);

        if (false === $isOwner){
            $qb->andWhere('d.isHidden = false');
        }

        return $qb->orderBy('d.createdAt', 'DESC')
            ->getQuery();
    }
}
