<?php

namespace Proxies\__CG__\Gdr\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Online extends \Gdr\UserBundle\Entity\Online implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'id', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'created', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'lastActivity', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'personage', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'location', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'isInGame', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'inGameEntered', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'inventoryBlockedUntil', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'isActive', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'status', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'isInvisible'];
        }

        return ['__isInitialized__', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'id', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'created', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'lastActivity', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'personage', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'location', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'isInGame', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'inGameEntered', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'inventoryBlockedUntil', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'isActive', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'status', '' . "\0" . 'Gdr\\UserBundle\\Entity\\Online' . "\0" . 'isInvisible'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Online $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastActivity($lastActivity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastActivity', [$lastActivity]);

        return parent::setLastActivity($lastActivity);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastActivity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastActivity', []);

        return parent::getLastActivity();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonage(\Gdr\UserBundle\Entity\Personage $personage = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonage', [$personage]);

        return parent::setPersonage($personage);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonage', []);

        return parent::getPersonage();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation(\Gdr\GameBundle\Entity\Location $location = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$location]);

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsInGame()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsInGame', []);

        return parent::getIsInGame();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsInGame($isInGame)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsInGame', [$isInGame]);

        return parent::setIsInGame($isInGame);
    }

    /**
     * {@inheritDoc}
     */
    public function setInGameEntered($inGameEntered)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInGameEntered', [$inGameEntered]);

        return parent::setInGameEntered($inGameEntered);
    }

    /**
     * {@inheritDoc}
     */
    public function getInGameEntered()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInGameEntered', []);

        return parent::getInGameEntered();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', []);

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', []);

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken($token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', [$token]);

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function setInventoryBlockedUntil($inventoryBlockedUntil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInventoryBlockedUntil', [$inventoryBlockedUntil]);

        return parent::setInventoryBlockedUntil($inventoryBlockedUntil);
    }

    /**
     * {@inheritDoc}
     */
    public function getInventoryBlockedUntil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInventoryBlockedUntil', []);

        return parent::getInventoryBlockedUntil();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsInvisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsInvisible', []);

        return parent::getIsInvisible();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsInvisible($isInvisible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsInvisible', [$isInvisible]);

        return parent::setIsInvisible($isInvisible);
    }

}
