<?php

namespace Gdr\RaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RaceLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceLevelRepository extends EntityRepository
{
    public function findByAgeAndRaceId($age, $race){
        return $this->createQueryBuilder("rl")
            ->andWhere("rl.race = :race")
            ->andWhere("rl.age_min <= :age")
            ->andWhere("rl.age_max >= :age")
            ->setParameter("age", $age)
            ->setParameter("race", $race)
            ->setMaxResults(1)
            ->getQuery()->getOneOrNullResult();
    }
}
