<?php

namespace Gdr\AdministrationBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class EnclaveCategoryAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Gdr\AdministrationBundle\Controller\EnclaveCategoryAdminController();
        return $instance;
    }
}
