<?php

namespace Gdr\GameBundle\Controller\Location;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BankController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Gdr\GameBundle\Controller\Location\BankController();
        return $instance;
    }
}
