<?php

namespace Gdr\GameBundle\Controller\Cron;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ChatMaintenanceController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Gdr\GameBundle\Controller\Cron\ChatMaintenanceController();
        return $instance;
    }
}
