<?php

namespace Gdr\GameBundle\Entity\Wise;

/**
 * WiseSentenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WiseSentenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllByTag(WiseTag $tag)
    {
        return $this
            ->createQueryBuilder('ws')
            ->join('ws.tags', 'wst')
            ->where('wst.id = :tag')
            ->setParameter('tag', $tag->getId())
            ->getQuery()
            ->getArrayResult();
    }
}
